### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by bschi** [ColonelJ/tron-transfers-downloader#5]
Hi,

I get an error. The download is not working for me. Is it possible to fix the error?

```
TypeError: Cannot read property 'block_timestamp' of null
at downloadAllTransactions (C:\download\index.js:58:35)
at processTicksAndRejections (node:internal/process/task_queues:94:5)
at async main (C:\download\index.js:343:17)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thanks and best regards!

**Comment by ColonelJ** [comment]
Hi @bschi this should be fixed in the latest version.  Again, it was a problem with TronGrid APIs, sometimes it erroneously returns null objects inside the response data.  The new code now retries the request to TronGrid if this is detected.
