### ISSUE TITLE
TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by fmando** [ColonelJ/tron-transfers-downloader#7]
What is missing?

> Writing to file output.csv...
TypeError: Cannot read property 'open' of undefined
    at main (/root/test/tron-transfers-downloader/index.js:355:32)
    at Object.<anonymous> (/root/test/tron-transfers-downloader/index.js:384:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
error Command failed with exit code 1.

> 

yarn --version
1.22.10

cat /etc/issue
Ubuntu 18.04.5 LTS \n \l

**Comment by fmando** [comment]
I think the node.js version was too old, tried it on another machine, worked but have a new issue.
