### ISSUE TITLE
TronGrid: Request failed with status code 403

### ISSUE THREAD

**Issue by fmando** [ColonelJ/tron-transfers-downloader#8]
Do i have to many transactions?

> Looking up TRC10 ID 1002072...
Looking up TRC10 ID 1002830...
Looking up TRC10 ID 1002814...
Looking up TRC10 ID 1002377...
Looking up TRC10 ID 1002578...
Looking up TRC10 ID 1002798...
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #1
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #2
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #3
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #4
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #5
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #6
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #7
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #8
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #9
Error querying TronGrid: Request failed with status code 403
Query TronGrid retry #10
Error querying TronGrid: Request failed with status code 403
Error: Multiple attempts to query TronGrid failed!
    at queryTronGrid (/root/tron-transfers-downloader/index.js:57:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.

>

**Comment by fmando** [comment]
Added a short delay in queryTronGrid function:

``
await new Promise(resolve => setTimeout(resolve, 55));
``


![image](https://user-images.githubusercontent.com/49414329/117862847-68049700-b293-11eb-9fd5-e6a65759db2d.png)


That helped me, thanks for coding.
